// src/features/time-attendance/domain/__tests__/attendance-overnight-attribution.test.ts
// Property test for overnight shift attribution.
//
// A shift whose end time is at or before its start time runs into the following
// calendar date, and Requirement 3, criterion 18 keeps the whole thing on the
// scheduled start date: every session belonging to the shift, and all of the
// scheduled hours. Split across two dates instead, a night shift would show up
// as two short days, one of them unscheduled.
//
// The clock-in is generated across the whole attribution window, both endpoints
// included, so the cases that matter — a session clocking in after local
// midnight, and one arriving inside the leading margin before the shift — are
// generated rather than hoped for. The counter at the end of the test asserts the
// after-midnight case actually occurred.
//
// A shift whose end equals its start belongs here too: the rule is `end <= start`,
// so that row describes a 24-hour shift rather than a zero-length one, and it is
// generated by `scheduleArb` often enough to matter.
//
// Feature: time-attendance-ui-redesign, Property 8: Overnight shift attribution
// **Validates: Requirements 3.18**

import { describe, expect, it } from 'vitest';
import fc from 'fast-check';
import {
  MINUTE_MS,
  attributeSessionWorkDate,
  deriveRange,
  resolveScheduleFacts,
  shiftAttributionWindows,
} from '../attendance';
import type { AttendanceInputs, AttendancePolicy, ClockSessionInput } from '../types';
import { addCalendarDays, workDateOf } from '../work-date';
import type { ScheduleInput } from './arbitraries';
import { attendancePolicyArb, scheduleArb, timeZoneArb, workDateArb } from './arbitraries';

/** Resolution of the position within the attribution window, in steps. */
const WINDOW_STEPS = 1_000;

/** `shift_end <= shift_start`: the shift ends on the following calendar date. */
const overnightScheduleArb = scheduleArb.filter((schedule) => schedule.end <= schedule.start);

function inputsFor(
  workDate: string,
  schedule: ScheduleInput | null,
  sessions: ClockSessionInput[],
  policy: AttendancePolicy,
  employeeTimezone: string,
  evaluatedAtMs: number,
): AttendanceInputs {
  return {
    profileId: 'overnight-property',
    workDate,
    employeeTimezone,
    schedule,
    sessions,
    approvedAbsence: null,
    unscheduledWorkApproved: false,
    reviewedAt: null,
    policy,
    evaluatedAt: new Date(evaluatedAtMs).toISOString(),
  };
}

describe('PBT-8: Overnight shift attribution', () => {
  it('attributes every session inside the window to the scheduled start date and contributes the scheduled hours to that date only', () => {
    let afterMidnightCases = 0;
    let leadingMarginCases = 0;

    fc.assert(
      fc.property(
        overnightScheduleArb,
        workDateArb,
        attendancePolicyArb,
        timeZoneArb,
        fc.integer({ min: 0, max: WINDOW_STEPS }),
        fc.integer({ min: 15, max: 8 * 60 }),
        (schedule, workDate, policy, employeeTimezone, windowStep, sessionMinutes) => {
          const facts = resolveScheduleFacts(workDate, schedule, policy);
          expect(facts).not.toBeNull();
          if (facts === null) return;

          // The generator's premise, restated as an assertion about the module.
          expect(facts.overnight).toBe(true);
          expect(facts.end.getTime()).toBeGreaterThan(facts.start.getTime());

          const windows = shiftAttributionWindows([{ workDate, schedule }], policy);
          expect(windows).toHaveLength(1);

          // A clock-in anywhere in the window, both endpoints inclusive.
          const windowMinutes =
            (facts.windowEnd.getTime() - facts.windowStart.getTime()) / MINUTE_MS;
          const offsetMinutes = Math.round((windowStep / WINDOW_STEPS) * windowMinutes);
          const clockInMs = facts.windowStart.getTime() + offsetMinutes * MINUTE_MS;
          const clockIn = new Date(clockInMs);

          // The session is attributed to the shift's scheduled start date, not
          // to the calendar date its clock-in falls on.
          expect(attributeSessionWorkDate(clockIn, employeeTimezone, windows)).toBe(workDate);

          const calendarDate = workDateOf(clockIn, employeeTimezone);
          if (calendarDate > workDate) afterMidnightCases += 1;
          if (clockInMs < facts.start.getTime()) leadingMarginCases += 1;

          // The shift contributes its scheduled hours to that date only: the
          // following date carries no schedule row and no session.
          const nextDate = addCalendarDays(workDate, 1);
          const session: ClockSessionInput = {
            id: 'overnight-session',
            clockIn: clockIn.toISOString(),
            clockOut: new Date(clockInMs + sessionMinutes * MINUTE_MS).toISOString(),
            breaks: [],
            adjustedBy: null,
            adjustmentReason: null,
          };
          const evaluatedAtMs = facts.windowEnd.getTime() + 60 * MINUTE_MS;

          const records = deriveRange([
            inputsFor(workDate, schedule, [session], policy, employeeTimezone, evaluatedAtMs),
            inputsFor(nextDate, null, [], policy, employeeTimezone, evaluatedAtMs),
          ]);
          expect(records).toHaveLength(2);

          const onStartDate = records[0];
          const onNextDate = records[1];
          expect(onStartDate.workDate).toBe(workDate);
          expect(onNextDate.workDate).toBe(nextDate);

          expect(onStartDate.scheduledHours).toBe(facts.scheduledHours);
          expect(onStartDate.scheduledHours).toBeGreaterThan(0);
          expect(onStartDate.scheduledStart).toBe(facts.start.toISOString());
          expect(onStartDate.scheduledEnd).toBe(facts.end.toISOString());

          expect(onNextDate.scheduledHours).toBe(0);
          expect(onNextDate.scheduledStart).toBeNull();
          expect(onStartDate.scheduledHours + onNextDate.scheduledHours).toBe(
            facts.scheduledHours,
          );

          expect(onStartDate.sessions.map((row) => row.id)).toEqual([session.id]);
          expect(onNextDate.sessions).toEqual([]);
        },
      ),
      { numRuns: 100 },
    );

    // Guard against a vacuous pass: attribution is only interesting where the
    // clock-in's own calendar date disagrees with the scheduled start date, and
    // where an early arrival sits in the margin ahead of the shift.
    expect(afterMidnightCases).toBeGreaterThan(0);
    expect(leadingMarginCases).toBeGreaterThan(0);
  });
});
