-- ═══════════════════════════════════════════════════════════════════════════════
-- v1.13.6 — Collector import
--
-- Spec: .kiro/specs/policy-follow-up-assignment-workflow
-- Requirements: 1.1, 1.2, 1.3, 1.4, 2.1, 2.2, 2.4, 2.5, 3.3, 4.1, 8.4, 11.2, 11.3, 13.1
-- Design: 11.1, 11.2
--
-- Forward-only. Two things:
--
--   1. `public.cancellation_import_batch` is replaced so it accepts the third column set,
--      `collector`. A consolidated collector export carries both halves of the legacy
--      eficacia/avisos pair, so it owns every field either half owned, plus contacts. The
--      merge logic itself is unchanged — this is the v1.10.10 body with each ownership
--      branch widened, generated by
--      `.kiro/specs/policy-follow-up-assignment-workflow/generate-collector-import-fn.mjs`
--      rather than retyped, and one extra `case_status` clause added for Requirement 8.4.
--
--      Both legacy paths keep behaving exactly as they did: `eficacia` and `avisos` still
--      own precisely the fields they owned, because every widened branch is
--      `in ('eficacia', 'collector')` or `in ('avisos', 'collector')` rather than a
--      reordering. The two-file transition path of the cancellations hardening spec is
--      untouched.
--
--   2. `public.renewal_import_collector_batch` is added beside `renewal_import_batch`. The
--      legacy Power BI / HawkSoft importer is left completely alone: it is still what the
--      current manager wizard calls, its column mapping still applies, and design 11.1's
--      requirement that a collector row not be labelled `powerbi` is met by having a
--      separate function that stamps `collector` and writes the source lineage.
--
-- ── What the renewal collector importer guarantees
--
--   * Re-import is idempotent (Requirement 2.4). Identity is `(policy_number, renewal_date)`,
--     the same pair the legacy importer uses, under the same advisory lock. A second run of
--     the same file updates source-owned facts and creates nothing.
--   * Source facts update; human work does not (Requirement 13.1). Notes, contacts, evidence,
--     the requote flag once set, a manager's `next_follow_up_at`, and a protected assignment
--     are never overwritten.
--   * A closed renewal is left closed (Requirement 2.5). Absence from a later file is not an
--     outcome, and neither is presence.
--   * Ownership follows the Requirement 3.3 precedence, by calling
--     `policy_followup_resolve_owner` per row after the upsert.
-- ═══════════════════════════════════════════════════════════════════════════════

do $pre$
begin
  if not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname = 'policy_followup_resolve_owner'
  ) then
    raise exception 'v1.13.6 requires v1.13.3' using hint = 'Nothing was changed.';
  end if;
  if not exists (
    select 1 from pg_constraint
     where conname = 'cancellation_import_runs_column_set_check'
       and pg_get_constraintdef(oid) like '%collector%'
  ) then
    raise exception 'v1.13.6 requires v1.13.2 (the collector column set must be accepted)'
      using hint = 'Nothing was changed.';
  end if;
  if not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname = 'cancellation_import_batch'
  ) then
    raise exception 'v1.13.6 requires v1.10.10' using hint = 'Nothing was changed.';
  end if;
end;
$pre$;

-- ===============================================================================
-- 1. CANCELLATION IMPORT: accept the consolidated collector column set
--
--    Generated from the v1.10.10 definition. Do not hand-edit: re-run
--    .kiro/specs/policy-follow-up-assignment-workflow/generate-collector-import-fn.mjs
--    and re-embed the output, so the merge logic keeps exactly one source.
-- ===============================================================================

create or replace function public.cancellation_import_batch(
  p_file_name text,
  p_column_set text,
  p_mapping jsonb,
  p_rows jsonb)
returns public.cancellation_import_runs
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_actor            uuid := auth.uid();
  v_run              public.cancellation_import_runs;
  v_rows             jsonb;
  v_counts           jsonb;
  v_element          jsonb;
  v_fields           jsonb;
  v_contacts         jsonb;
  v_header           text[];
  v_row_header       text[];
  v_row_number       integer;
  v_assigned         uuid;
  v_raw_row          jsonb;
  v_case_id          uuid;
  v_created          boolean;
  v_row_contacts     bigint;
  v_row_invalid      bigint;
  v_rows_created     integer := 0;
  v_rows_updated     integer := 0;
  v_contacts_stored  bigint := 0;
  v_invalid_stored   bigint := 0;
  v_rows_total       integer;
  v_rows_rejected    integer;
  v_rows_duplicate   integer;
  v_split            integer;
  v_case_status      text;
begin
  -- ── Caller authorization (Requirement 8.5)
  if not public.cancellation_is_manager() then
    raise exception 'cancellation_import_batch is reserved to Manager_Role'
      using errcode = 'insufficient_privilege',
            detail  = 'Requirement 8.5: no Cancellation_Case row and no Contact_Recipient row is created until a manager confirms the displayed preview.',
            hint    = 'Nothing was written.';
  end if;

  if v_actor is null then
    raise exception 'cancellation_import_batch could not identify the importing profile'
      using errcode = 'insufficient_privilege', hint = 'Nothing was written.';
  end if;

  if p_file_name is null or length(btrim(p_file_name)) = 0 then
    raise exception 'cancellation_import_batch needs the imported file name'
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  if p_column_set is null or p_column_set not in ('eficacia', 'avisos', 'collector') then
    raise exception 'cancellation_import_batch needs a column set of eficacia, avisos, or collector (got %)',
                    coalesce(p_column_set, 'null')
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  if p_mapping is null or jsonb_typeof(p_mapping) <> 'object' then
    raise exception 'cancellation_import_batch needs the confirmed mapping as a JSON object'
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  -- ── Payload resolution (same as v1.10.5)
  if p_rows is null then
    raise exception 'cancellation_import_batch needs a row payload'
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  elsif jsonb_typeof(p_rows) = 'array' then
    v_rows   := p_rows;
    v_counts := null;
  elsif jsonb_typeof(p_rows) = 'object' then
    v_rows   := coalesce(p_rows -> 'rows', p_rows -> 'plan');
    v_counts := coalesce(p_rows -> 'counts', p_rows - 'rows' - 'plan');
  else
    raise exception 'cancellation_import_batch needs p_rows as a JSON array or object (got %)',
                    jsonb_typeof(p_rows)
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  if v_rows is null or jsonb_typeof(v_rows) <> 'array' then
    raise exception 'cancellation_import_batch found no row array in p_rows'
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  if v_counts is not null and jsonb_typeof(v_counts) <> 'object' then
    v_counts := null;
  end if;

  -- ── raw_header from confirmed mapping
  if jsonb_typeof(p_mapping -> 'header') = 'array' then
    select array_agg(value order by ord)
      into v_header
      from jsonb_array_elements_text(p_mapping -> 'header') with ordinality as t(value, ord);
  end if;

  if v_header is null or cardinality(v_header) = 0 then
    raise exception 'cancellation_import_batch needs the source header in p_mapping.header'
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  -- ── Count validation
  v_rows_total     := coalesce((v_counts ->> 'rows_total')::integer, jsonb_array_length(v_rows));
  v_rows_rejected  := coalesce((v_counts ->> 'rows_rejected')::integer, 0);
  v_rows_duplicate := coalesce((v_counts ->> 'rows_duplicate')::integer, 0);
  v_split          := coalesce((v_counts ->> 'rows_created')::integer, 0)
                    + coalesce((v_counts ->> 'rows_updated')::integer, 0);

  if v_counts ? 'rows_created' and v_counts ? 'rows_updated'
     and v_split <> jsonb_array_length(v_rows) then
    raise exception 'cancellation_import_batch got a created/updated split of % for % rows',
                    v_split, jsonb_array_length(v_rows)
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  if v_rows_total <> jsonb_array_length(v_rows) + v_rows_rejected + v_rows_duplicate then
    raise exception 'cancellation_import_batch got rows_total % for % loading, % rejected, % duplicate rows',
                    v_rows_total, jsonb_array_length(v_rows), v_rows_rejected, v_rows_duplicate
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  -- ── Import audit entry (Requirement 8.8)
  insert into public.cancellation_import_runs (
    file_name, column_set, imported_by, confirmed_mapping,
    rows_total, rows_created, rows_updated, rows_rejected, rows_duplicate,
    rejected_rows, duplicate_rows, unmatched_producer_labels, unmatched_customer_rows,
    amount_due_absent_rows, invalid_contact_count, contact_overflow_count)
  values (
    p_file_name, p_column_set, v_actor, p_mapping,
    v_rows_total, 0, 0, v_rows_rejected, v_rows_duplicate,
    case when jsonb_typeof(v_counts -> 'rejected_rows') = 'array'
         then v_counts -> 'rejected_rows' else '[]'::jsonb end,
    case when jsonb_typeof(v_counts -> 'duplicate_rows') = 'array'
         then v_counts -> 'duplicate_rows' else '[]'::jsonb end,
    case when jsonb_typeof(v_counts -> 'unmatched_producer_labels') = 'array'
         then v_counts -> 'unmatched_producer_labels' else '[]'::jsonb end,
    case when jsonb_typeof(v_counts -> 'unmatched_customer_rows') = 'array'
         then v_counts -> 'unmatched_customer_rows' else '[]'::jsonb end,
    case when jsonb_typeof(v_counts -> 'amount_due_absent_rows') = 'array'
         then v_counts -> 'amount_due_absent_rows' else '[]'::jsonb end,
    coalesce((v_counts ->> 'invalid_contact_count')::integer, 0),
    coalesce((v_counts ->> 'contact_overflow_count')::integer, 0))
  returning * into v_run;

  -- ── Process each row
  for v_element in
    select t.value
      from jsonb_array_elements(v_rows) with ordinality as t(value, ord)
     order by t.ord
  loop
    if jsonb_typeof(v_element) <> 'object' then
      raise exception 'cancellation_import_batch got a % where a row object was expected',
                      jsonb_typeof(v_element)
        using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
    end if;

    v_fields := case when v_element ? 'fields'
                     then (v_element -> 'fields') || (v_element - 'fields' - 'contacts')
                     else v_element - 'contacts' end;

    v_contacts := case
      when jsonb_typeof(v_element -> 'contacts') = 'array' then v_element -> 'contacts'
      when jsonb_typeof(v_element -> 'contacts' -> 'rows') = 'array' then v_element -> 'contacts' -> 'rows'
      else '[]'::jsonb
    end;

    v_row_number := coalesce(nullif(v_fields ->> 'source_row_number', '')::integer,
                             nullif(v_fields ->> 'row_number', '')::integer,
                             nullif(v_fields ->> 'rowNumber', '')::integer);
    v_assigned   := nullif(v_fields ->> 'assigned_to', '')::uuid;
    v_raw_row    := v_fields -> 'raw_row';
    v_case_status := nullif(btrim(coalesce(v_fields ->> 'case_status', '')), '');

    if nullif(btrim(coalesce(v_fields ->> 'policy_number', '')), '') is null then
      raise exception 'cancellation_import_batch got row % with no policy number',
                      coalesce(v_row_number, 0)
        using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
    end if;

    if nullif(v_fields ->> 'cancellation_effective_date', '') is null then
      raise exception 'cancellation_import_batch got row % with no cancellation effective date',
                      coalesce(v_row_number, 0)
        using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
    end if;

    if v_raw_row is null or jsonb_typeof(v_raw_row) <> 'array' then
      raise exception 'cancellation_import_batch got row % without raw_row as a JSON array',
                      coalesce(v_row_number, 0)
        using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
    end if;

    if jsonb_typeof(v_fields -> 'raw_header') = 'array' then
      select array_agg(value order by ord)
        into v_row_header
        from jsonb_array_elements_text(v_fields -> 'raw_header') with ordinality as t(value, ord);
    else
      v_row_header := v_header;
    end if;

    -- ── Upsert with SOURCE-AWARE MERGE (REQ-1.1, REQ-1.2, REQ-1.3)
    -- The ON CONFLICT DO UPDATE branch uses COALESCE to never overwrite populated
    -- values with null from the other source. Field ownership is determined by
    -- p_column_set parameter.
    insert into public.cancellation_cases (
      policy_number, cancellation_effective_date,
      customer_name, client_identifier, customer_match_key, carrier, amount_due,
      case_status, communication_status,
      assigned_to, assignment_source, producer_label,
      legacy_send_flag, legacy_state, legacy_result, legacy_notices_sent,
      legacy_first_notice, legacy_last_notice, legacy_days_remaining,
      legacy_notice_label, legacy_subject, legacy_email_body, legacy_sms_body,
      raw_row, raw_header, import_run_id, source_row_number)
    values (
      v_fields ->> 'policy_number',
      (v_fields ->> 'cancellation_effective_date')::date,
      v_fields ->> 'customer_name',
      v_fields ->> 'client_identifier',
      v_fields ->> 'customer_match_key',
      v_fields ->> 'carrier',
      nullif(v_fields ->> 'amount_due', '')::numeric,
      -- REQ-2.1: use derived status for creates, default to Imported if absent
      coalesce(v_case_status, 'Imported'),
      'Not Scheduled',
      v_assigned,
      case when v_assigned is not null then 'import' end,
      v_fields ->> 'producer_label',
      v_fields ->> 'legacy_send_flag',
      v_fields ->> 'legacy_state',
      v_fields ->> 'legacy_result',
      v_fields ->> 'legacy_notices_sent',
      v_fields ->> 'legacy_first_notice',
      v_fields ->> 'legacy_last_notice',
      v_fields ->> 'legacy_days_remaining',
      v_fields ->> 'legacy_notice_label',
      v_fields ->> 'legacy_subject',
      v_fields ->> 'legacy_email_body',
      v_fields ->> 'legacy_sms_body',
      v_raw_row,
      v_row_header,
      v_run.id,
      v_row_number)
    on conflict on constraint cancellation_cases_identity_key do update set
       -- EFICACIA-owned fields: written by eficacia, preserved by avisos
       -- Avisos may update customer_name/carrier only when non-empty (REQ-1.2)
       customer_name = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.customer_name, cancellation_cases.customer_name)
         else coalesce(nullif(btrim(excluded.customer_name), ''), cancellation_cases.customer_name)
       end,
       carrier = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.carrier, cancellation_cases.carrier)
         else coalesce(nullif(btrim(excluded.carrier), ''), cancellation_cases.carrier)
       end,
       -- These are eficacia-only; avisos never carries them
       client_identifier = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.client_identifier, cancellation_cases.client_identifier)
         else cancellation_cases.client_identifier
       end,
       customer_match_key = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.customer_match_key, cancellation_cases.customer_match_key)
         else cancellation_cases.customer_match_key
       end,
       amount_due = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.amount_due, cancellation_cases.amount_due)
         else cancellation_cases.amount_due
       end,
       producer_label = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.producer_label, cancellation_cases.producer_label)
         else cancellation_cases.producer_label
       end,
       -- Eficacia legacy fields
       legacy_send_flag = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.legacy_send_flag, cancellation_cases.legacy_send_flag)
         else cancellation_cases.legacy_send_flag
       end,
       legacy_state = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.legacy_state, cancellation_cases.legacy_state)
         else cancellation_cases.legacy_state
       end,
       legacy_result = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.legacy_result, cancellation_cases.legacy_result)
         else cancellation_cases.legacy_result
       end,
       legacy_notices_sent = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.legacy_notices_sent, cancellation_cases.legacy_notices_sent)
         else cancellation_cases.legacy_notices_sent
       end,
       legacy_first_notice = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.legacy_first_notice, cancellation_cases.legacy_first_notice)
         else cancellation_cases.legacy_first_notice
       end,
       legacy_last_notice = case
         when p_column_set in ('eficacia', 'collector') then coalesce(excluded.legacy_last_notice, cancellation_cases.legacy_last_notice)
         else cancellation_cases.legacy_last_notice
       end,
       -- AVISOS-owned legacy fields: written by avisos, preserved by eficacia
       legacy_days_remaining = case
         when p_column_set in ('avisos', 'collector') then coalesce(excluded.legacy_days_remaining, cancellation_cases.legacy_days_remaining)
         else cancellation_cases.legacy_days_remaining
       end,
       legacy_notice_label = case
         when p_column_set in ('avisos', 'collector') then coalesce(excluded.legacy_notice_label, cancellation_cases.legacy_notice_label)
         else cancellation_cases.legacy_notice_label
       end,
       legacy_subject = case
         when p_column_set in ('avisos', 'collector') then coalesce(excluded.legacy_subject, cancellation_cases.legacy_subject)
         else cancellation_cases.legacy_subject
       end,
       legacy_email_body = case
         when p_column_set in ('avisos', 'collector') then coalesce(excluded.legacy_email_body, cancellation_cases.legacy_email_body)
         else cancellation_cases.legacy_email_body
       end,
       legacy_sms_body = case
         when p_column_set in ('avisos', 'collector') then coalesce(excluded.legacy_sms_body, cancellation_cases.legacy_sms_body)
         else cancellation_cases.legacy_sms_body
       end,
       -- case_status: only update if eficacia provides a non-null derived status
       -- and the current status is still 'Imported' (never downgrade manager changes)
       case_status = case
         when p_column_set in ('eficacia', 'collector') and v_case_status is not null
              and cancellation_cases.case_status = 'Imported'
           then v_case_status
         -- v1.13.6: a collector paid or review signal may also move a case that is already
         -- Open, which is what stops future reminders (Requirement 8.4). It is bounded to
         -- Imported and Open, so it can never undo a manager's advance and can never resolve
         -- a case: `Cancelled` is not in the list, and the collector only proposes it when the
         -- identity is unambiguous, which the importer resolves before it gets here.
         when p_column_set = 'collector'
              and v_case_status in ('Payment Reported', 'Import Review Required')
              and cancellation_cases.case_status in ('Imported', 'Open')
           then v_case_status
         else cancellation_cases.case_status
       end,
       -- Raw row and provenance: always update to latest
       raw_row           = excluded.raw_row,
       raw_header        = excluded.raw_header,
       import_run_id     = excluded.import_run_id,
       source_row_number = excluded.source_row_number,
       -- Assignment: manager outranks, unresolved clears nothing (Req 9.8)
       assigned_to = case
         when cancellation_cases.assignment_source = 'manager'
           then cancellation_cases.assigned_to
         else coalesce(excluded.assigned_to, cancellation_cases.assigned_to)
       end,
       assignment_source = case
         when cancellation_cases.assignment_source = 'manager' then 'manager'
         when excluded.assigned_to is not null then 'import'
         else cancellation_cases.assignment_source
       end,
       updated_at = now()
    returning id, (xmax::text = '0') into v_case_id, v_created;

    if v_created then
      v_rows_created := v_rows_created + 1;
    else
      v_rows_updated := v_rows_updated + 1;
    end if;

    -- ── Preserve raw row in audit table (REQ-1.4)
    insert into public.cancellation_import_case_rows (
      case_id, import_run_id, source_row_number, raw_row, raw_header, column_set)
    values (
      v_case_id, v_run.id, coalesce(v_row_number, 0), v_raw_row, v_row_header, p_column_set);

    -- ── Contact rows (same dedup logic as v1.10.5)
    if jsonb_typeof(v_contacts) = 'array' and jsonb_array_length(v_contacts) > 0 then
      with incoming as (
        select distinct on (c.channel, c.normalized_value)
               c.channel, c.normalized_value, c.raw_segment, c.validation_status,
               c.authorization_status, c.sms_suppressed, c.email_suppressed,
               c.is_primary, c.preferred_language, c.preferred_channel,
               c.contact_name, c.contact_role, c.segment_index
          from jsonb_to_recordset(v_contacts) as c(
                 channel text, normalized_value text, raw_segment text,
                 validation_status text, authorization_status text,
                 sms_suppressed boolean, email_suppressed boolean,
                 is_primary boolean, preferred_language text, preferred_channel text,
                 contact_name text, contact_role text, segment_index integer)
         order by c.channel, c.normalized_value, coalesce(c.segment_index, 0)
      ), stored as (
        insert into public.cancellation_contacts (
          case_id, channel, normalized_value, raw_segment, validation_status,
          authorization_status, sms_suppressed, email_suppressed, is_primary,
          preferred_language, preferred_channel, contact_name, contact_role, segment_index)
        select v_case_id, i.channel, i.normalized_value,
               coalesce(i.raw_segment, i.normalized_value), i.validation_status,
               coalesce(i.authorization_status, 'Unknown'),
               coalesce(i.sms_suppressed, false), coalesce(i.email_suppressed, false),
               coalesce(i.is_primary, false), i.preferred_language, i.preferred_channel,
               i.contact_name, i.contact_role, coalesce(i.segment_index, 0)
          from incoming i
        on conflict on constraint cancellation_contacts_dedup_key do nothing
        returning validation_status
      )
      select count(*), count(*) filter (where validation_status = 'invalid')
        into v_row_contacts, v_row_invalid
        from stored;
    else
      v_row_contacts := 0;
      v_row_invalid  := 0;
    end if;

    v_contacts_stored := v_contacts_stored + coalesce(v_row_contacts, 0);
    v_invalid_stored  := v_invalid_stored + coalesce(v_row_invalid, 0);

    -- ── Audit timeline event
    insert into public.cancellation_events (case_id, actor_id, event_type, detail)
    values (
      v_case_id, v_actor,
      case when v_created then 'imported' else 'import_updated' end,
      jsonb_build_object(
        'import_run_id',     v_run.id,
        'file_name',         p_file_name,
        'column_set',        p_column_set,
        'source_row_number', v_row_number,
        'outcome',           case when v_created then 'created' else 'updated' end,
        'contacts_created',  coalesce(v_row_contacts, 0),
        'producer_label',    v_fields ->> 'producer_label',
        'import_assignment', v_assigned));
  end loop;

  -- ── Final counts
  update public.cancellation_import_runs
     set rows_created = v_rows_created,
         rows_updated = v_rows_updated,
         invalid_contact_count = case
           when v_counts ? 'invalid_contact_count' then invalid_contact_count
           else v_invalid_stored
         end
   where id = v_run.id
  returning * into v_run;

  return v_run;
end;
$fn$;

comment on function public.cancellation_import_batch(text, text, jsonb, jsonb) is
  'Loads one confirmed cancellation import. Source-aware merge: eficacia owns the case facts, avisos owns the notice/message text and the contacts, and the consolidated collector export owns both because it carries both. COALESCE throughout, so a blank value from any source never overwrites a populated one. Requirements 2.2, 2.4, 8.4, and the cancellations hardening REQ-1.1 through REQ-1.4.';

-- ═══════════════════════════════════════════════════════════════════════════════
-- 2. RENEWAL COLLECTOR IMPORT (Requirements 2.1, 2.4, 2.5, 3.3, 11.2, 13.1)
--
--    Beside `renewal_import_batch`, not instead of it. The legacy importer keeps its column
--    mapping, its `powerbi` assignment source, and its missing-from-latest-file sweep; this
--    one reads the 26-column consolidated export, which needs no mapping, and writes the
--    source lineage the legacy path has nowhere to put.
--
--    `p_rows` is the array `buildRenewalCollectorPayload` produces in
--    src/features/policy-follow-up/collector.ts. Every field name below is a key of that type,
--    so the two sides are checkable against each other by reading them side by side.
-- ═══════════════════════════════════════════════════════════════════════════════

create or replace function public.renewal_import_collector_batch(
  p_file_name text,
  p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_run_id uuid := gen_random_uuid();
  v_imported_at timestamptz := now();
  v_actor uuid := auth.uid();
  v_business_date date := (now() at time zone 'America/New_York')::date;

  v_row jsonb;
  v_policy text;
  v_date date;
  v_customer text;
  v_existing public.renewal_records;
  v_record_id uuid;
  v_before jsonb;
  v_after jsonb;
  v_outcome jsonb;

  v_total integer := 0;
  v_inserted integer := 0;
  v_updated integer := 0;
  v_skipped integer := 0;
  v_closed integer := 0;
  v_review integer := 0;
  v_nonrenewal integer := 0;

  -- Requirement 11.2: the import summary must distinguish how each row came to be owned.
  v_kept_owner integer := 0;
  v_producer_assigned integer := 0;
  v_weighted_assigned integer := 0;
  v_manager_locked integer := 0;
  v_unassigned integer := 0;
  v_conflicts integer := 0;

  v_unmatched_labels text[] := array[]::text[];
  v_label text;
begin
  if not public.policy_followup_is_manager() then
    raise exception 'Manager access is required to import a renewal collector file.'
      using errcode = 'insufficient_privilege', hint = 'Nothing was written.';
  end if;

  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'renewal_import_collector_batch needs a JSON array of rows'
      using errcode = 'invalid_parameter_value', hint = 'Nothing was written.';
  end if;

  -- The same advisory lock the legacy importer takes, so a collector import and a Power BI
  -- import cannot interleave on the same identity.
  perform pg_advisory_xact_lock(709130013);

  for v_row in select value from jsonb_array_elements(p_rows)
  loop
    v_total := v_total + 1;

    v_policy := nullif(btrim(coalesce(v_row ->> 'policy_number', '')), '');
    begin v_date := nullif(v_row ->> 'renewal_date', '')::date;
    exception when others then v_date := null; end;
    v_customer := nullif(btrim(coalesce(v_row ->> 'customer_name', '')), '');

    -- The three values `renewal_records` cannot do without. The client already rejected these
    -- rows and reported them by row number; this is the server refusing to be talked into one.
    if v_policy is null or v_date is null or v_customer is null then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    if coalesce((v_row ->> 'source_review_required')::boolean, false) then
      v_review := v_review + 1;
    end if;
    if v_row ->> 'source_state_normalized' = 'carrier_nonrenewal' then
      v_nonrenewal := v_nonrenewal + 1;
    end if;

    select * into v_existing
      from public.renewal_records record
     where record.policy_number = v_policy
       and record.renewal_date = v_date
     order by record.created_at
     limit 1
     for update;

    if found then
      -- Requirement 2.5: a recorded outcome is a human decision. A later file neither
      -- reopens it nor changes it, and absence from a file is not an outcome either.
      if v_existing.status::text in ('renewed', 'lost', 'cancelled') then
        v_closed := v_closed + 1;
        continue;
      end if;

      v_before := to_jsonb(v_existing);

      update public.renewal_records record
         set -- ── Source-owned facts (Requirement 13.1). COALESCE throughout, so a blank
             --    collector cell never erases a value a manager corrected by hand.
             customer_name    = coalesce(v_customer, record.customer_name),
             carrier          = coalesce(nullif(btrim(coalesce(v_row ->> 'carrier', '')), ''), record.carrier),
             line_of_business = coalesce(nullif(btrim(coalesce(v_row ->> 'line_of_business', '')), ''),
                                         record.line_of_business),
             hawksoft_client_id = coalesce(nullif(btrim(coalesce(v_row ->> 'hawksoft_client_id', '')), ''),
                                           record.hawksoft_client_id),
             customer_phone   = coalesce(nullif(btrim(coalesce(v_row ->> 'customer_phone', '')), ''),
                                         record.customer_phone),
             customer_email   = coalesce(nullif(btrim(coalesce(v_row ->> 'customer_email', '')), ''),
                                         record.customer_email),
             premium_current  = coalesce((v_row ->> 'premium_current')::numeric, record.premium_current),
             premium_renewal  = coalesce((v_row ->> 'premium_renewal')::numeric, record.premium_renewal),
             expiration_date  = coalesce(nullif(v_row ->> 'expiration_date', '')::date, record.expiration_date),
             producer_label   = coalesce(nullif(btrim(coalesce(v_row ->> 'producer_label', '')), ''),
                                         record.producer_label),

             -- ── Source lineage (Requirement 1.1). Always the latest run's values: this *is*
             --    the answer to "what did the newest file say", and the previous answer lives
             --    in the renewal_events entry written below.
             source_system                 = 'renewal_collector',
             source_record_type            = v_row ->> 'source_record_type',
             source_status_raw             = v_row ->> 'source_status_raw',
             source_state_normalized       = v_row ->> 'source_state_normalized',
             source_match_status           = v_row ->> 'source_match_status',
             source_match_method           = v_row ->> 'source_match_method',
             source_match_status_raw       = v_row ->> 'source_match_status_raw',
             source_file_name              = coalesce(nullif(btrim(coalesce(p_file_name, '')), ''),
                                                      v_row ->> 'source_file_name'),
             source_row_number             = nullif(v_row ->> 'source_row_number', '')::integer,
             source_warning                = v_row ->> 'source_warning',
             source_review_required        = coalesce((v_row ->> 'source_review_required')::boolean, false),
             source_communication_blocked  = coalesce((v_row ->> 'source_communication_blocked')::boolean, false),
             source_payload                = coalesce(v_row -> 'source_payload', record.source_payload),

             -- ── Sync bookkeeping, shared with the legacy importer.
             last_seen_import_run_id = v_run_id,
             last_seen_imported_at   = v_imported_at,
             source_sync_state       = 'present',
             missing_since_import_run_id = null,
             updated_at              = v_imported_at

             -- Deliberately NOT written here (Requirement 13.1): assigned_to,
             -- assignment_source, status, next_follow_up_at, requote_requested, requote_note,
             -- import_notes, outcome_reason. Ownership is the assignment engine's to decide
             -- below; the rest is human work.
       where record.id = v_existing.id;

      v_record_id := v_existing.id;
      select to_jsonb(record) into v_after from public.renewal_records record where record.id = v_record_id;
      v_updated := v_updated + 1;

      insert into public.renewal_events(record_id, actor_id, event_type, detail)
      values (v_record_id, v_actor, 'collector_record_updated',
              jsonb_build_object('file_name', p_file_name, 'run_id', v_run_id,
                                 'source_row_number', v_row ->> 'source_row_number',
                                 'before', v_before, 'after', v_after));
    else
      insert into public.renewal_records(
        status, policy_number, renewal_date, customer_name, customer_phone, customer_email,
        carrier, line_of_business, hawksoft_client_id,
        premium_current, premium_renewal, expiration_date, producer_label,
        source_system, source_record_type, source_status_raw, source_state_normalized,
        source_match_status, source_match_method, source_match_status_raw,
        source_file_name, source_row_number, source_warning,
        source_review_required, source_communication_blocked, source_payload,
        last_seen_import_run_id, last_seen_imported_at, source_sync_state)
      values (
        'imported'::public.renewal_status, v_policy, v_date, v_customer,
        nullif(btrim(coalesce(v_row ->> 'customer_phone', '')), ''),
        nullif(btrim(coalesce(v_row ->> 'customer_email', '')), ''),
        nullif(btrim(coalesce(v_row ->> 'carrier', '')), ''),
        nullif(btrim(coalesce(v_row ->> 'line_of_business', '')), ''),
        nullif(btrim(coalesce(v_row ->> 'hawksoft_client_id', '')), ''),
        (v_row ->> 'premium_current')::numeric,
        (v_row ->> 'premium_renewal')::numeric,
        nullif(v_row ->> 'expiration_date', '')::date,
        nullif(btrim(coalesce(v_row ->> 'producer_label', '')), ''),
        'renewal_collector',
        v_row ->> 'source_record_type',
        v_row ->> 'source_status_raw',
        v_row ->> 'source_state_normalized',
        v_row ->> 'source_match_status',
        v_row ->> 'source_match_method',
        v_row ->> 'source_match_status_raw',
        coalesce(nullif(btrim(coalesce(p_file_name, '')), ''), v_row ->> 'source_file_name'),
        nullif(v_row ->> 'source_row_number', '')::integer,
        v_row ->> 'source_warning',
        coalesce((v_row ->> 'source_review_required')::boolean, false),
        coalesce((v_row ->> 'source_communication_blocked')::boolean, false),
        v_row -> 'source_payload',
        v_run_id, v_imported_at, 'present')
      returning id into v_record_id;

      v_inserted := v_inserted + 1;

      insert into public.renewal_events(record_id, actor_id, event_type, detail)
      values (v_record_id, v_actor, 'collector_record_created',
              jsonb_build_object('file_name', p_file_name, 'run_id', v_run_id,
                                 'source_row_number', v_row ->> 'source_row_number',
                                 'source_state_normalized', v_row ->> 'source_state_normalized',
                                 'producer_label', v_row ->> 'producer_label'));
    end if;

    -- ── Ownership: the Requirement 3.3 precedence, per row, after the facts are stored.
    v_outcome := public.policy_followup_resolve_owner('renewal', v_record_id, v_business_date, true);

    case v_outcome ->> 'reason'
      when 'manager_locked' then v_manager_locked := v_manager_locked + 1;
      when 'existing_owner' then v_kept_owner := v_kept_owner + 1;
      when 'domain_owner_bootstrap' then v_kept_owner := v_kept_owner + 1;
      when 'producer_mapping' then v_producer_assigned := v_producer_assigned + 1;
      when 'weighted_auto' then v_weighted_assigned := v_weighted_assigned + 1;
      when 'ownership_conflict' then v_conflicts := v_conflicts + 1;
      else v_unassigned := v_unassigned + 1;
    end case;

    -- Requirement 9.3: a producer label the one agency mapping does not know is a manager
    -- exception, reported by label rather than by row.
    if v_outcome ->> 'reason' = 'manager_review_unmatched_producer' then
      v_label := nullif(btrim(coalesce(v_row ->> 'producer_label', '')), '');
      if v_label is not null and not (v_label = any(v_unmatched_labels)) then
        v_unmatched_labels := array_append(v_unmatched_labels, v_label);
      end if;
    end if;
  end loop;

  -- The run is recorded in the same table the legacy importer uses, so the manager Imports
  -- surface lists both kinds of run in one history. `column_mapping` carries the collector
  -- marker rather than a mapping, because a collector export needs none.
  insert into public.renewal_import_runs(
    id, file_name, imported_by, column_mapping, rows_total, rows_inserted, rows_updated,
    rows_skipped, rows_closed_preserved, rows_assigned, rows_requote_flagged,
    unmatched_assignees, distinct_assignee_labels)
  values (
    v_run_id,
    coalesce(nullif(btrim(coalesce(p_file_name, '')), ''), 'consolidado_renovaciones.csv'),
    v_actor,
    jsonb_build_object('source', 'renewal_collector', 'mapping_required', false),
    v_total, v_inserted, v_updated, v_skipped, v_closed,
    v_producer_assigned + v_weighted_assigned,
    v_nonrenewal,
    to_jsonb(v_unmatched_labels),
    cardinality(v_unmatched_labels));

  return jsonb_build_object(
    'id', v_run_id,
    'rows_total', v_total,
    'rows_inserted', v_inserted,
    'rows_updated', v_updated,
    'rows_skipped', v_skipped,
    'rows_closed_preserved', v_closed,
    'rows_review_required', v_review,
    'rows_carrier_nonrenewal', v_nonrenewal,
    -- Requirement 11.2: import success and assignment completion are different questions.
    'assignment', jsonb_build_object(
      'manager_locked', v_manager_locked,
      'existing_owner', v_kept_owner,
      'producer_mapping', v_producer_assigned,
      'weighted_auto', v_weighted_assigned,
      'ownership_conflict', v_conflicts,
      'unassigned_review', v_unassigned),
    'unmatched_producer_labels', to_jsonb(v_unmatched_labels));
end;
$fn$;

comment on function public.renewal_import_collector_batch(text, jsonb) is
  'Loads one consolidated Renewals collector export (Requirement 2.1). Persists the source lineage beside the normalized interpretation, updates source-owned facts without touching human work, leaves a closed renewal closed, and resolves ownership through the Requirement 3.3 precedence per row. Reports the assignment outcome by source, which Requirement 11.2 distinguishes from import success. Separate from renewal_import_batch, which keeps the legacy Power BI path unchanged.';

grant execute on function public.renewal_import_collector_batch(text, jsonb) to authenticated;

-- ═══════════════════════════════════════════════════════════════════════════════
-- 3. POST-CONDITIONS
-- ═══════════════════════════════════════════════════════════════════════════════
do $post$
declare
  v_definition text;
begin
  if not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname = 'renewal_import_collector_batch'
  ) then
    raise exception 'v1.13.6 did not create renewal_import_collector_batch' using hint = 'Rolling back.';
  end if;

  select pg_get_functiondef(p.oid) into v_definition
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'cancellation_import_batch';

  -- The collector column set is accepted.
  if v_definition not like '%''eficacia'', ''avisos'', ''collector''%' then
    raise exception 'cancellation_import_batch still refuses the collector column set'
      using detail = 'Requirement 2.2.', hint = 'Rolling back.';
  end if;

  -- Every ownership branch is collector-inclusive, and none was left narrow.
  if v_definition ~ 'p_column_set = ''eficacia''' then
    raise exception 'cancellation_import_batch left an eficacia-only ownership branch'
      using detail = 'Design 11.2: a collector export owns both halves.', hint = 'Rolling back.';
  end if;
  if v_definition ~ 'p_column_set = ''avisos''' then
    raise exception 'cancellation_import_batch left an avisos-only ownership branch'
      using detail = 'Design 11.2: a collector export owns both halves.', hint = 'Rolling back.';
  end if;

  -- The legacy pair is still named in every widened branch, so neither legacy path changed
  -- which fields it owns.
  if v_definition not like '%in (''eficacia'', ''collector'')%'
     or v_definition not like '%in (''avisos'', ''collector'')%' then
    raise exception 'cancellation_import_batch lost one of the legacy column sets'
      using hint = 'Rolling back.';
  end if;

  -- The Requirement 8.4 clause that lets a collector paid signal reach an already-Open case.
  if v_definition not like '%p_column_set = ''collector''%' then
    raise exception 'cancellation_import_batch is missing the collector paid-signal clause'
      using detail = 'Requirement 8.4.', hint = 'Rolling back.';
  end if;

  raise notice 'v1.13.6 applied: both collector exports import, and the two legacy cancellation paths are unchanged.';
end;
$post$;
