-- New Hope Work Desk — ROLLBACK for v1.8.7-fix-rotation-integrity
--
-- AUTO-GENERATED by .kiro/specs/queue-rotation-integrity/scripts/generate-rollback.mjs
-- Captured from the LIVE database at 2026-07-31T03:41:33.657Z
-- immediately before v1.8.7 was applied.
--
-- WHAT THIS DOES
--   * Restores the 6 replaced functions to the exact bodies that were
--     running in production before v1.8.7.
--   * Drops the 5 helper functions v1.8.7 introduced.
--
-- WHAT THIS DELIBERATELY DOES NOT DO
--   * It does NOT rewrite public.rotation_state. A rotation left pointing at a
--     valid agent is harmless under the old functions, and rewriting it could
--     strand a live turn.
--   * It contains NO INSERT / UPDATE / DELETE / TRUNCATE / DROP TABLE.
--   * No quote, work item, intake, turn_events, quote_take_events, audit_log or
--     any other data row is read-modified-written. All history is preserved.
--
-- WARNING
--   Restoring these bodies REINTRODUCES the wraparound defect (RC-1): rotations
--   will again go NULL or stick on one agent whenever the current agent holds the
--   highest eligible position. Only run this if v1.8.7 caused a worse problem.
--
-- After running, re-run:
--   .kiro/specs/queue-rotation-integrity/diagnostics/production-queue-diagnostic.sql

begin;


-- ═══════════════════════════════════════════════════════════════════════════════
-- 1. Drop the helper functions introduced by v1.8.7.
--    Dropped AFTER the originals are restored below would fail on dependency, so
--    the restores come first and these drops run last (section 3).
-- ═══════════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════════
-- 2. Restore the pre-v1.8.7 function bodies verbatim.
-- ═══════════════════════════════════════════════════════════════════════════════


-- ── public.next_eligible_profile(public.rotation_kind,integer) ──
-- Live ACL at capture time: =X/postgres | postgres=X/postgres | anon=X/postgres | authenticated=X/postgres | service_role=X/postgres
CREATE OR REPLACE FUNCTION public.next_eligible_profile(p_rotation rotation_kind, p_after_position integer)
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT p.id
  FROM public.profiles p
  WHERE p.is_active
    AND p.role = 'agent'
    AND p.availability = 'available'
    AND CASE
      WHEN p_rotation = 'whatsapp' THEN p.whatsapp_active
      WHEN p_rotation = 'ringcentral' THEN p.ringcentral_active
      ELSE p.workload_active
    END
    AND CASE
      WHEN p_rotation = 'whatsapp' THEN p.whatsapp_position > p_after_position
      WHEN p_rotation = 'ringcentral' THEN p.ringcentral_position > p_after_position
      ELSE p.workload_position > p_after_position
    END
  ORDER BY
    CASE
      WHEN p_rotation = 'whatsapp' THEN p.whatsapp_position
      WHEN p_rotation = 'ringcentral' THEN p.ringcentral_position
      ELSE p.workload_position
    END
  LIMIT 1;
$function$;


-- ── public.pass_my_turn(public.rotation_kind,text) ──
-- Live ACL at capture time: postgres=X/postgres | authenticated=X/postgres | service_role=X/postgres
CREATE OR REPLACE FUNCTION public.pass_my_turn(p_rotation rotation_kind, p_reason text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_me public.profiles%rowtype;
  v_state public.rotation_state%rowtype;
  v_next uuid;
begin
  if not public.is_agent() then raise exception 'Agent permission required'; end if;
  if p_rotation = 'workload' then
    raise exception 'Additional Workload turns cannot be passed. Take the task and use Customer Service overflow after acceptance when needed.';
  end if;
  if nullif(trim(p_reason), '') is null then raise exception 'A pass reason is required'; end if;

  perform public.ensure_daily_availability_reset();

  select * into v_me from public.profiles where id = auth.uid() and is_active for update;
  if not found then raise exception 'Active profile not found'; end if;

  select * into v_state from public.rotation_state where kind = p_rotation for update;
  if v_state.current_profile_id is distinct from v_me.id then raise exception 'This turn belongs to another agent'; end if;

  v_next := public.next_eligible_profile(
    p_rotation,
    case when p_rotation = 'whatsapp' then v_me.whatsapp_position else v_me.ringcentral_position end
  );
  if v_next is null then raise exception 'No eligible next agent'; end if;

  update public.rotation_state
  set current_profile_id = v_next,
      version = version + 1,
      updated_at = now(),
      updated_by = v_me.id
  where kind = p_rotation;

  insert into public.turn_events(rotation, action, actor_profile_id, previous_profile_id, next_profile_id, reason)
  values (p_rotation, 'pass', v_me.id, v_me.id, v_next, btrim(p_reason));

  return v_next;
end;
$function$;


-- ── public.set_my_availability(public.availability_status) ──
-- Live ACL at capture time: postgres=X/postgres | authenticated=X/postgres | service_role=X/postgres
CREATE OR REPLACE FUNCTION public.set_my_availability(p_status availability_status)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_me public.profiles%rowtype;
  v_rotation public.rotation_state%rowtype;
  v_next uuid;
  v_previous uuid;
  v_eligible boolean;
  v_current_usable boolean;
  v_started_today boolean;
begin
  if not public.is_agent() then raise exception 'Agent permission required'; end if;

  perform public.ensure_daily_availability_reset();

  select * into v_me
  from public.profiles
  where id = auth.uid() and is_active
  for update;

  if not found then raise exception 'Active profile not found'; end if;

  update public.profiles
  set availability = p_status
  where id = v_me.id;

  if p_status = 'available' then
    for v_rotation in select * from public.rotation_state order by kind for update loop
      v_eligible := case
        when v_rotation.kind = 'whatsapp' then v_me.whatsapp_active
        when v_rotation.kind = 'ringcentral' then v_me.ringcentral_active
        else v_me.workload_active
      end;

      if v_eligible then
        if v_rotation.current_profile_id is null then
          select exists (
            select 1
            from public.daily_rotation_starts d
            where d.business_date = public.current_business_date()
              and d.rotation = v_rotation.kind
          ) into v_started_today;

          if not v_started_today then
            insert into public.daily_rotation_starts(business_date, rotation, starter_profile_id)
            values (public.current_business_date(), v_rotation.kind, v_me.id)
            on conflict (business_date, rotation) do nothing;
          end if;

          update public.rotation_state
          set current_profile_id = v_me.id,
              version = version + 1,
              updated_at = now(),
              updated_by = v_me.id
          where kind = v_rotation.kind;

          insert into public.turn_events(rotation, action, actor_profile_id, previous_profile_id, next_profile_id, reason)
          values (
            v_rotation.kind,
            case when v_started_today then 'auto_skip' else 'daily_start' end,
            v_me.id,
            null,
            v_me.id,
            case when v_started_today then 'Empty queue resumed when an eligible agent became available' else 'First eligible agent available for the business day' end
          );
        else
          select exists (
            select 1 from public.profiles p
            where p.id = v_rotation.current_profile_id
              and p.is_active
              and p.role = 'agent'
              and p.availability = 'available'
              and case
                when v_rotation.kind = 'whatsapp' then p.whatsapp_active
                when v_rotation.kind = 'ringcentral' then p.ringcentral_active
                else p.workload_active
              end
          ) into v_current_usable;

          if not v_current_usable then
            v_previous := v_rotation.current_profile_id;

            update public.rotation_state
            set current_profile_id = v_me.id,
                version = version + 1,
                updated_at = now(),
                updated_by = v_me.id
            where kind = v_rotation.kind;

            insert into public.turn_events(rotation, action, actor_profile_id, previous_profile_id, next_profile_id, reason)
            values (v_rotation.kind, 'auto_skip', v_me.id, v_previous, v_me.id, 'Stale queue corrected when an eligible agent became available');
          end if;
        end if;
      end if;
    end loop;
  else
    for v_rotation in select * from public.rotation_state order by kind for update loop
      if v_rotation.current_profile_id = v_me.id then
        v_next := public.next_eligible_profile(
          v_rotation.kind,
          case
            when v_rotation.kind = 'whatsapp' then v_me.whatsapp_position
            when v_rotation.kind = 'ringcentral' then v_me.ringcentral_position
            else v_me.workload_position
          end
        );

        update public.rotation_state
        set current_profile_id = v_next,
            version = version + 1,
            updated_at = now(),
            updated_by = v_me.id
        where kind = v_rotation.kind;

        insert into public.turn_events(rotation, action, actor_profile_id, previous_profile_id, next_profile_id, reason)
        values (
          v_rotation.kind,
          'auto_skip',
          v_me.id,
          v_me.id,
          v_next,
          case when v_next is null then 'Agent became unavailable and no eligible agent is currently available' else 'Agent became unavailable' end
        );
      end if;
    end loop;
  end if;
end;
$function$;


-- ── public.manager_set_rotation_eligibility(uuid,public.rotation_kind,boolean,text) ──
-- Live ACL at capture time: postgres=X/postgres | authenticated=X/postgres | service_role=X/postgres
CREATE OR REPLACE FUNCTION public.manager_set_rotation_eligibility(p_profile_id uuid, p_rotation rotation_kind, p_active boolean, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_old jsonb;
  v_profile public.profiles%rowtype;
  v_state public.rotation_state%rowtype;
  v_next uuid;
  v_position integer;
begin
  if not public.can_manage_sales() then raise exception 'Manager permission required'; end if;
  if nullif(trim(p_reason), '') is null then raise exception 'A reason is required'; end if;

  select * into v_profile from public.profiles where id = p_profile_id for update;
  if not found or v_profile.role <> 'agent' then raise exception 'Active agent not found'; end if;
  v_old := to_jsonb(v_profile);

  if p_rotation = 'whatsapp' then
    update public.profiles set whatsapp_active = p_active where id = p_profile_id;
    v_position := v_profile.whatsapp_position;
  elsif p_rotation = 'ringcentral' then
    update public.profiles set ringcentral_active = p_active where id = p_profile_id;
    v_position := v_profile.ringcentral_position;
  else
    update public.profiles set workload_active = p_active where id = p_profile_id;
    v_position := v_profile.workload_position;
  end if;

  -- Pausing the current agent must not leave the queue stuck on someone who cannot act.
  if not p_active then
    select * into v_state from public.rotation_state where kind = p_rotation for update;
    if v_state.current_profile_id = p_profile_id then
      v_next := public.next_eligible_profile(p_rotation, v_position);
      if v_next is not null and v_next <> p_profile_id then
        update public.rotation_state
        set current_profile_id = v_next, version = version + 1, updated_at = now(), updated_by = auth.uid()
        where kind = p_rotation;

        insert into public.turn_events(rotation, action, actor_profile_id, previous_profile_id, next_profile_id, reason)
        values (p_rotation, 'auto_skip', auth.uid(), p_profile_id, v_next, 'Manager paused current agent from queue');
      end if;
    end if;
  end if;

  insert into public.audit_log(actor_profile_id, action, entity_type, entity_id, old_value, new_value, reason)
  select auth.uid(), 'rotation_eligibility_changed', 'profile', p_profile_id, v_old, to_jsonb(p), p_reason
  from public.profiles p where p.id = p_profile_id;
end;
$function$;


-- ── public.claim_timed_quote(uuid) ──
-- Live ACL at capture time: postgres=X/postgres | authenticated=X/postgres | service_role=X/postgres
CREATE OR REPLACE FUNCTION public.claim_timed_quote(p_timer_id uuid)
 RETURNS work_items
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_timer public.quote_take_timers%rowtype;
  v_state public.rotation_state%rowtype;
  v_current public.profiles%rowtype;
  v_item public.work_items%rowtype;
  v_next uuid;
  v_position integer;
  v_elapsed integer;
begin
  if not public.is_agent() then raise exception 'Agent permission required'; end if;

  select * into v_timer
  from public.quote_take_timers
  where id = p_timer_id
  for update;
  if not found or v_timer.status <> 'active' then raise exception 'This rescue timer is no longer active'; end if;
  if v_timer.current_profile_id <> auth.uid() then raise exception 'This timed quote belongs to the current queue agent'; end if;

  select * into v_state
  from public.rotation_state
  where kind = v_timer.rotation
  for update;
  if v_state.current_profile_id is distinct from v_timer.current_profile_id then raise exception 'The queue moved and this timer is no longer valid'; end if;

  select * into v_current
  from public.profiles
  where id = v_timer.current_profile_id and role = 'agent' and is_active;
  if not found then raise exception 'Current agent profile is invalid'; end if;

  insert into public.work_items(
    customer_name, dealer_id, work_type, assigned_profile_id, assignment_method,
    status, note, received_through, created_by, assigned_at, accepted_at
  ) values (
    v_timer.customer_name, v_timer.dealer_id, v_timer.work_type, v_current.id,
    case when v_timer.rotation = 'whatsapp' then 'whatsapp_turn'::public.assignment_method else 'ringcentral_turn'::public.assignment_method end,
    'active', v_timer.note,
    case when v_timer.rotation = 'whatsapp' then 'WhatsApp dealership' else 'RingCentral' end,
    v_current.id, now(), now()
  ) returning * into v_item;

  v_elapsed := greatest(0, floor(extract(epoch from (now() - v_timer.received_at)))::integer);

  update public.quote_take_timers
  set status = 'claimed', claimed_by_profile_id = v_current.id,
      source_work_item_id = v_item.id, completed_at = now()
  where id = v_timer.id;

  perform public.add_quote_note_if_present(v_item.id, v_current.id, v_timer.note);

  insert into public.work_item_events(source_work_item_id, event_type, actor_profile_id, assigned_profile_id, details, created_at)
  values (
    v_item.id, 'timer_claimed', v_current.id, v_current.id,
    jsonb_build_object('timer_id', v_timer.id, 'received_at', v_timer.received_at, 'elapsed_seconds', v_elapsed),
    now()
  );

  v_position := case when v_timer.rotation = 'whatsapp' then v_current.whatsapp_position else v_current.ringcentral_position end;
  v_next := public.next_eligible_profile(v_timer.rotation, v_position);

  update public.rotation_state
  set current_profile_id = v_next, version = version + 1,
      updated_at = now(), updated_by = v_current.id
  where kind = v_timer.rotation;

  insert into public.turn_events(rotation, action, actor_profile_id, previous_profile_id, next_profile_id, work_item_id, reason)
  values (v_timer.rotation, 'claim', v_current.id, v_current.id, v_next, v_item.id, 'Current agent responded to rescue timer');

  return v_item;
end;
$function$;


-- ── public.steal_timed_quote(uuid) ──
-- Live ACL at capture time: postgres=X/postgres | authenticated=X/postgres | service_role=X/postgres
CREATE OR REPLACE FUNCTION public.steal_timed_quote(p_timer_id uuid)
 RETURNS work_items
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_timer public.quote_take_timers%rowtype;
  v_state public.rotation_state%rowtype;
  v_current public.profiles%rowtype;
  v_me public.profiles%rowtype;
  v_item public.work_items%rowtype;
  v_next uuid;
  v_position integer;
  v_elapsed integer;
begin
  if not public.is_agent() then raise exception 'Agent permission required'; end if;

  select * into v_timer
  from public.quote_take_timers
  where id = p_timer_id
  for update;
  if not found or v_timer.status <> 'active' then raise exception 'This rescue timer is no longer active'; end if;
  if v_timer.deadline_at > now() then raise exception 'The current agent still has time remaining'; end if;
  if v_timer.current_profile_id = auth.uid() then raise exception 'You own this turn. Use Take Timed Quote instead'; end if;

  select * into v_me
  from public.profiles
  where id = auth.uid() and role = 'agent' and is_active
  for update;
  if not found then raise exception 'Active agent profile not found'; end if;
  if v_me.availability <> 'available' then raise exception 'Set your status to Available before stealing a quote'; end if;
  if v_timer.rotation = 'whatsapp' and not v_me.whatsapp_active then raise exception 'You are paused from the WhatsApp queue'; end if;
  if v_timer.rotation = 'ringcentral' and not v_me.ringcentral_active then raise exception 'You are paused from the RingCentral queue'; end if;

  select * into v_state
  from public.rotation_state
  where kind = v_timer.rotation
  for update;
  if v_state.current_profile_id is distinct from v_timer.current_profile_id then raise exception 'The queue moved and this timer is no longer valid'; end if;

  select * into v_current
  from public.profiles
  where id = v_timer.current_profile_id and role = 'agent' and is_active;
  if not found then raise exception 'The missed agent profile is invalid'; end if;

  insert into public.work_items(
    customer_name, dealer_id, work_type, assigned_profile_id, assignment_method,
    status, note, received_through, created_by, assigned_at, accepted_at
  ) values (
    v_timer.customer_name, v_timer.dealer_id, v_timer.work_type, v_me.id,
    case when v_timer.rotation = 'whatsapp' then 'whatsapp_turn'::public.assignment_method else 'ringcentral_turn'::public.assignment_method end,
    'active', v_timer.note,
    case when v_timer.rotation = 'whatsapp' then 'WhatsApp dealership' else 'RingCentral' end,
    v_me.id, now(), now()
  ) returning * into v_item;

  v_elapsed := greatest(0, floor(extract(epoch from (now() - v_timer.received_at)))::integer);

  update public.quote_take_timers
  set status = 'stolen', claimed_by_profile_id = v_me.id,
      source_work_item_id = v_item.id, completed_at = now()
  where id = v_timer.id;

  insert into public.quote_take_events(
    source_work_item_id, rotation, received_at, taken_at,
    taker_profile_id, skipped_profile_ids, elapsed_seconds
  ) values (
    v_item.id, v_timer.rotation, v_timer.received_at, now(),
    v_me.id, array[v_current.id]::uuid[], v_elapsed
  );

  perform public.add_quote_note_if_present(v_item.id, v_me.id, v_timer.note);

  insert into public.work_item_events(source_work_item_id, event_type, actor_profile_id, assigned_profile_id, details, created_at)
  values (
    v_item.id, 'taken', v_me.id, v_me.id,
    jsonb_build_object(
      'timer_id', v_timer.id,
      'rotation', v_timer.rotation,
      'received_at', v_timer.received_at,
      'elapsed_seconds', v_elapsed,
      'missed_profile_id', v_current.id,
      'skipped_profile_ids', to_jsonb(array[v_current.id]::uuid[])
    ),
    now()
  );

  -- Preserve queue order: advance from the employee whose turn expired.
  v_position := case when v_timer.rotation = 'whatsapp' then v_current.whatsapp_position else v_current.ringcentral_position end;
  v_next := public.next_eligible_profile(v_timer.rotation, v_position);

  update public.rotation_state
  set current_profile_id = v_next, version = version + 1,
      updated_at = now(), updated_by = v_me.id
  where kind = v_timer.rotation;

  insert into public.turn_events(rotation, action, actor_profile_id, previous_profile_id, next_profile_id, work_item_id, reason)
  values (
    v_timer.rotation, 'claim', v_me.id, v_current.id, v_next, v_item.id,
    format('Quote stolen after %s seconds; missed current agent %s', v_elapsed, v_current.display_name)
  );

  insert into public.user_notifications(
    recipient_profile_id, notification_type, title, message, entity_type, entity_id
  ) values (
    v_current.id,
    'turn',
    'Quote was stolen',
    format('%s took %s after your 3-minute response period expired. Your turn was consumed and the regular queue order was preserved.', v_me.display_name, v_timer.customer_name),
    'work_item',
    v_item.id
  );

  return v_item;
end;
$function$;


-- ═══════════════════════════════════════════════════════════════════════════════
-- 3. Drop the v1.8.7 helpers (now unreferenced by the restored bodies).
-- ═══════════════════════════════════════════════════════════════════════════════

drop function if exists public.advance_rotation(public.rotation_kind,uuid,integer,text,uuid,uuid,uuid,text);
drop function if exists public.ensure_rotation_valid(public.rotation_kind,uuid);
drop function if exists public.is_rotation_eligible(uuid,public.rotation_kind);
drop function if exists public.rotation_position_of(uuid,public.rotation_kind);
drop function if exists public.rotation_empty_reason(public.rotation_kind);


-- ═══════════════════════════════════════════════════════════════════════════════
-- 4. Restore grants exactly as captured above.
-- ═══════════════════════════════════════════════════════════════════════════════
grant execute on function public.next_eligible_profile(public.rotation_kind, integer) to anon, authenticated, service_role;
grant execute on function public.pass_my_turn(public.rotation_kind, text) to authenticated, service_role;
grant execute on function public.set_my_availability(public.availability_status) to authenticated, service_role;
grant execute on function public.manager_set_rotation_eligibility(uuid, public.rotation_kind, boolean, text) to authenticated, service_role;
grant execute on function public.claim_timed_quote(uuid) to authenticated, service_role;
grant execute on function public.steal_timed_quote(uuid) to authenticated, service_role;

-- ═══════════════════════════════════════════════════════════════════════════════
-- 5. Verify the rollback landed.
-- ═══════════════════════════════════════════════════════════════════════════════
do $verify$
begin
  if to_regprocedure('public.advance_rotation(public.rotation_kind,uuid,integer,text,uuid,uuid,uuid,text)') is not null then
    raise exception 'rollback incomplete: advance_rotation still exists';
  end if;
  if to_regprocedure('public.ensure_rotation_valid(public.rotation_kind,uuid)') is not null then
    raise exception 'rollback incomplete: ensure_rotation_valid still exists';
  end if;
  raise notice 'v1.8.7 rolled back. The RC-1 wraparound defect is now present again.';
end
$verify$;

commit;
