'use client';

// src/features/quotes/IntakeNoteLog.tsx
// Renders the pre-formatted Intake Note Log text with visual structure.
// Handles both Personal Auto and Commercial Auto formats generated by
// the _generate_intake_note_log Supabase function.

interface IntakeNoteLogProps {
  content: string; // The formatted note log text from quote_history_events.note_log_content
}

/**
 * Parse the note log content into structured blocks for rendering.
 * The raw text uses:
 *   ═══ INTAKE NOTE LOG ═══   — metadata header line
 *   ───────────────────────   — separator after metadata
 *   ▸ SECTION_NAME            — section headers
 *   Two-space indented lines  — field values within sections
 */
export function parseNoteLog(content: string) {
  const lines = content.split('\n');

  const metadataLines: string[] = [];
  const sections: { title: string; lines: string[] }[] = [];

  let inMetadata = true;
  let currentSection: { title: string; lines: string[] } | null = null;

  for (const line of lines) {
    // Detect header boundary (separator line ends metadata block)
    if (inMetadata && line.startsWith('───')) {
      inMetadata = false;
      continue;
    }

    // Metadata region — everything before the separator
    if (inMetadata) {
      // Skip the ═══ header decoration line itself
      if (line.startsWith('═══')) continue;
      if (line.trim()) metadataLines.push(line);
      continue;
    }

    // Section header
    if (line.startsWith('▸ ')) {
      if (currentSection) sections.push(currentSection);
      currentSection = { title: line.slice(2).trim(), lines: [] };
      continue;
    }

    // Field line within a section
    if (currentSection) {
      // Keep non-empty lines (skip blank lines between sections)
      if (line.trim()) {
        currentSection.lines.push(line);
      }
    }
  }

  // Push last section if exists
  if (currentSection) sections.push(currentSection);

  return { metadataLines, sections };
}

export default function IntakeNoteLog({ content }: IntakeNoteLogProps) {
  if (!content || !content.trim()) {
    return (
      <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">
        No intake note log available.
      </div>
    );
  }

  const { metadataLines, sections } = parseNoteLog(content);

  return (
    <div className="rounded-lg border border-slate-200 bg-white font-mono text-[13px] leading-relaxed shadow-sm">
      {/* Metadata header */}
      {metadataLines.length > 0 && (
        <div className="border-b border-slate-200 bg-slate-50 px-4 py-3">
          <div className="mb-1 text-xs font-semibold uppercase tracking-wider text-slate-500">
            Intake Note Log
          </div>
          {metadataLines.map((line, i) => (
            <div key={i} className="text-slate-600">
              {line}
            </div>
          ))}
        </div>
      )}

      {/* Sections */}
      <div className="divide-y divide-slate-100 px-4 py-2">
        {sections.map((section, idx) => (
          <div key={idx} className="py-3">
            <div className="mb-1.5 flex items-center gap-1.5 text-xs font-bold uppercase tracking-wide text-indigo-700">
              <span className="text-indigo-400">&#9656;</span>
              {section.title}
            </div>
            <div className="space-y-0.5 pl-3 text-slate-700">
              {section.lines.map((line, li) => (
                <div key={li} className="whitespace-pre-wrap">
                  {line}
                </div>
              ))}
            </div>
          </div>
        ))}

        {sections.length === 0 && (
          <div className="py-3 text-slate-400">No sections found in note log.</div>
        )}
      </div>
    </div>
  );
}
